--------------------------------------------------------
--  File created - Tuesday-January-19-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOT_CAMP_TEAM1_USERS
--------------------------------------------------------

  CREATE TABLE "BOOT_PROJECT_TEAM1"."BOOT_CAMP_TEAM1_USERS" 
   (	"USERNAME" VARCHAR2(30 CHAR), 
	"PASSWORD" VARCHAR2(30 CHAR), 
	"RECORD_ID" NUMBER, 
	"ACTIVE" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOOT_PROJECT_TEAM1.BOOT_CAMP_TEAM1_USERS
SET DEFINE OFF;
Insert into BOOT_PROJECT_TEAM1.BOOT_CAMP_TEAM1_USERS (USERNAME,PASSWORD,RECORD_ID,ACTIVE) values ('ankur','Password1#',66,null);
Insert into BOOT_PROJECT_TEAM1.BOOT_CAMP_TEAM1_USERS (USERNAME,PASSWORD,RECORD_ID,ACTIVE) values ('ashley','Password1#',67,null);
Insert into BOOT_PROJECT_TEAM1.BOOT_CAMP_TEAM1_USERS (USERNAME,PASSWORD,RECORD_ID,ACTIVE) values ('ilayaraja','Password1#',68,null);
--------------------------------------------------------
--  DDL for Index USERS_PK_RECORD_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOT_PROJECT_TEAM1"."USERS_PK_RECORD_ID" ON "BOOT_PROJECT_TEAM1"."BOOT_CAMP_TEAM1_USERS" ("RECORD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOT_CAMP_TEAM1_USERS
--------------------------------------------------------

  ALTER TABLE "BOOT_PROJECT_TEAM1"."BOOT_CAMP_TEAM1_USERS" MODIFY ("RECORD_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOT_PROJECT_TEAM1"."BOOT_CAMP_TEAM1_USERS" ADD CONSTRAINT "USERS_PK_RECORD_ID" PRIMARY KEY ("RECORD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
