--------------------------------------------------------
--  File created - Tuesday-January-19-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "BOOT_PROJECT_TEAM1"."PRODUCT" 
   (	"RECORD_ID" NUMBER, 
	"PRODUCT_ID" VARCHAR2(30 CHAR), 
	"PRODUCT_FAMILY" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"REMARKS" VARCHAR2(500 CHAR), 
	"ADMINISTRABLE_DOSE_FORM" VARCHAR2(30 CHAR), 
	"MAIN_INGREDIENT" NUMBER, 
	"ACTIVE" VARCHAR2(3 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOOT_PROJECT_TEAM1.PRODUCT
SET DEFINE OFF;
Insert into BOOT_PROJECT_TEAM1.PRODUCT (RECORD_ID,PRODUCT_ID,PRODUCT_FAMILY,PRODUCT_NAME,DESCRIPTION,REMARKS,ADMINISTRABLE_DOSE_FORM,MAIN_INGREDIENT,ACTIVE) values (249,'PRD-103',264,'Product 103','																																												',null,'Oral',261,'Yes');
Insert into BOOT_PROJECT_TEAM1.PRODUCT (RECORD_ID,PRODUCT_ID,PRODUCT_FAMILY,PRODUCT_NAME,DESCRIPTION,REMARKS,ADMINISTRABLE_DOSE_FORM,MAIN_INGREDIENT,ACTIVE) values (324,'PRD-161',264,'Product 161','				','				','Nasal',323,'Yes');
Insert into BOOT_PROJECT_TEAM1.PRODUCT (RECORD_ID,PRODUCT_ID,PRODUCT_FAMILY,PRODUCT_NAME,DESCRIPTION,REMARKS,ADMINISTRABLE_DOSE_FORM,MAIN_INGREDIENT,ACTIVE) values (281,'PRD-124',264,'Product- 124','				',null,'Nasal',263,'Yes');
Insert into BOOT_PROJECT_TEAM1.PRODUCT (RECORD_ID,PRODUCT_ID,PRODUCT_FAMILY,PRODUCT_NAME,DESCRIPTION,REMARKS,ADMINISTRABLE_DOSE_FORM,MAIN_INGREDIENT,ACTIVE) values (341,'PRD-181',264,'Prd181','				','				','Nasal',323,'No');
--------------------------------------------------------
--  DDL for Index SYS_C00671522
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOT_PROJECT_TEAM1"."SYS_C00671522" ON "BOOT_PROJECT_TEAM1"."PRODUCT" ("RECORD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "BOOT_PROJECT_TEAM1"."PRODUCT" ADD CONSTRAINT "PRD_PK_RECORD_ID" PRIMARY KEY ("RECORD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "BOOT_PROJECT_TEAM1"."PRODUCT" ADD CONSTRAINT "PRD_FK_MAIN_INGR" FOREIGN KEY ("MAIN_INGREDIENT")
	  REFERENCES "BOOT_PROJECT_TEAM1"."SUBSTANCE" ("RECORD_ID") ENABLE;
  ALTER TABLE "BOOT_PROJECT_TEAM1"."PRODUCT" ADD CONSTRAINT "PRD_FK_PRD_FAMILY" FOREIGN KEY ("PRODUCT_FAMILY")
	  REFERENCES "BOOT_PROJECT_TEAM1"."PRODUCT_FAMILY" ("RECORD_ID") ENABLE;
