--------------------------------------------------------
--  File created - Tuesday-January-19-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT_FAMILY
--------------------------------------------------------

  CREATE TABLE "BOOT_PROJECT_TEAM1"."PRODUCT_FAMILY" 
   (	"RECORD_ID" NUMBER, 
	"PRODUCT_FAMILY_UID" VARCHAR2(30 CHAR), 
	"PRODUCT_FAMILY_NAME" VARCHAR2(50 CHAR), 
	"REMARKS" VARCHAR2(2000 CHAR), 
	"ACTIVE" VARCHAR2(3 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOOT_PROJECT_TEAM1.PRODUCT_FAMILY
SET DEFINE OFF;
Insert into BOOT_PROJECT_TEAM1.PRODUCT_FAMILY (RECORD_ID,PRODUCT_FAMILY_UID,PRODUCT_FAMILY_NAME,REMARKS,ACTIVE) values (265,'PF-162','ProductFamily- 162','				','Yes');
Insert into BOOT_PROJECT_TEAM1.PRODUCT_FAMILY (RECORD_ID,PRODUCT_FAMILY_UID,PRODUCT_FAMILY_NAME,REMARKS,ACTIVE) values (264,'PF-161','ProductFamily- 161',null,'Yes');
--------------------------------------------------------
--  DDL for Index PRD_FAMILY_PK_RECORD_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOT_PROJECT_TEAM1"."PRD_FAMILY_PK_RECORD_ID" ON "BOOT_PROJECT_TEAM1"."PRODUCT_FAMILY" ("RECORD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRD_FAMILY_UK_PRD_FAMILY_UID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOT_PROJECT_TEAM1"."PRD_FAMILY_UK_PRD_FAMILY_UID" ON "BOOT_PROJECT_TEAM1"."PRODUCT_FAMILY" ("PRODUCT_FAMILY_UID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRD_FAMILY_UK_PRD_FAMILY_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOT_PROJECT_TEAM1"."PRD_FAMILY_UK_PRD_FAMILY_NAME" ON "BOOT_PROJECT_TEAM1"."PRODUCT_FAMILY" ("PRODUCT_FAMILY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT_FAMILY
--------------------------------------------------------

  ALTER TABLE "BOOT_PROJECT_TEAM1"."PRODUCT_FAMILY" ADD CONSTRAINT "PRD_FAMILY_PK_RECORD_ID" PRIMARY KEY ("RECORD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOT_PROJECT_TEAM1"."PRODUCT_FAMILY" ADD CONSTRAINT "PRD_FAMILY_UK_PRD_FAMILY_NAME" UNIQUE ("PRODUCT_FAMILY_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOT_PROJECT_TEAM1"."PRODUCT_FAMILY" ADD CONSTRAINT "PRD_FAMILY_UK_PRD_FAMILY_UID" UNIQUE ("PRODUCT_FAMILY_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
